FROM python:3.10.12-slim

WORKDIR /app

COPY ./manga_scraper ./manga_scraper

COPY ./aws_utils ./aws_utils

RUN pip install --no-cache-dir -r ./manga_scraper/requirements.txt

CMD ["python3", "-m", "manga_scraper.main"]
