name: "AWS Login pipeline"

env:
  ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME}} 
  AWS_REGION: ${{ secrets.AWS_REGION}} 


on:
  push:
    branches:
      - main
    # paths:
    paths-ignore:
      - .github/**  
      - docs/**
      - README.md

  pull_request:
    branches:
      - main
    # paths:
    paths-ignore:
      - .github/**   
      - docs/**
      - README.md

permissions:
  id-token: write
  pull-requests: write
  contents: read    # This is required for actions/checkout

jobs:
  Build:
    name: "AWS Login"
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout the repository to the runner 
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: Build-GitHub

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
